services:
  - type: web
    name: social-organizer
    env: node
    rootDir: socialiser     ← This tells Render where your app is
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
